name: Build APK
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install buildozer
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk zip
      - name: Setup Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          mkdir -p /usr/local/lib/android/sdk/cmdline-tools
          unzip commandlinetools-linux-9477386_latest.zip -d /usr/local/lib/android/sdk/cmdline-tools
          mv /usr/local/lib/android/sdk/cmdline-tools/cmdline-tools /usr/local/lib/android/sdk/cmdline-tools/latest
          echo "ANDROID_HOME=/usr/local/lib/android/sdk" >> $GITHUB_ENV
          echo "PATH=$PATH:/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> $GITHUB_ENV
      - name: Build APK
        run: |
          yes | buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: parastar-apk
          path: bin/*.apk
